# Exercise 3 (part 2/3)

For this exercise you can use either Python with sklearn or Weka.

* Using the UCI mushroom dataset from the last exercise, perform a feature selection using a classifier evaluator. Which features are most discriminitave?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

shroom_data = pd.read_csv("agaricus-lepiota.data", header=None)
df = pd.DataFrame(shroom_data)
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
count,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124,...,8124,8124,8124,8124,8124,8124,8124,8124,8124,8124
unique,2,6,4,10,2,9,2,2,2,12,...,4,9,9,1,4,3,5,9,6,7
top,e,x,y,n,f,n,f,c,b,b,...,s,w,w,p,w,o,p,w,v,d
freq,4208,3656,3244,2284,4748,3528,7914,6812,5612,1728,...,4936,4464,4384,8124,7924,7488,3968,2388,4040,3148



* Use principal components analysis to construct a reduced space. Which combination of features explain the most variance in the dataset?



* Do you see any overlap between the PCA features and those obtained from feature selection?